name: rolling

on:
  pull_request:
    branches:
      - rolling
    paths-ignore:
      - 'README.md'
  push:
    branches:
      - rolling
    paths-ignore:
      - 'README.md'
  schedule:
      - cron: '0 0 * * 1'
jobs:
  build-and-test:
    runs-on: ubuntu-26.04
    container:
      # Use the pre-built setup-ros-docker image here instead of standard ubuntu
      image: ghcr.io/ros-tooling/setup-ros-docker/setup-ros-docker-ubuntu-resolute-ros-rolling-ros-base:master
    steps:
      - name: Build and test
        uses: ros-tooling/action-ros-ci@0.4.8
        with:
          package-name: gpe_core gpe_msgs gpe_landmark_server gpe_offline_estimation
          import-token: ${{ secrets.GITHUB_TOKEN }}
          target-ros2-distro: rolling
          colcon-defaults: |
            {
              "test": {
                "parallel-workers" : 1
              }
            }
          # vcs-repo-file-url: ${GITHUB_WORKSPACE}/dependency_repos.repos
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
